### ISSUE TITLE
TimeCopDateTime should extend DateTime

### ISSUE THREAD

**Issue by kagux** [hnw/php-timecop#1]
As `new DateTime` returns an instance of `TimeCopDateTime` it breaks all methods that expect instance of `DateTime`.
This only happens when I execute php through php-fpm. Inheritance works fine in CLI

**Comment by francisbesset** [comment]
The base of problem is the TypeHinting:
```php
function dump_date(DateTime $date) {
  var_dump($date);
}
dump_date(new DateTime());
```

But this issue can be closed because TimecopDateTime is an instance of DateTime from v1.1.0.
```php
var_dump(new TimecopDateTime instanceof DateTime);
var_dump(new TimecopDateTime instanceof DateTimeInterface);
```
