### ISSUE TITLE
Timecop segfaults when set_error_handler throws an exception

### ISSUE THREAD

**Issue by JonLoesch** [hnw/php-timecop#10]
mktime is a function that according to the documentation you are not supposed to call without arguments.  When you call mktime (the built-in PHP version) with no arguments it returns successfully, but emits a E_STRICT error/warning that says:

>   "PHP Strict Standards:  mktime(): You should be using the time() function instead in php shell code on line 1"

After this module is installed, it instead emits: 

>   "PHP Strict Standards:  timecop_mktime(): You should be using the time() function instead in php shell code on line 1"

So that's the same behaviour (except for a changed function name).  However, if you have the practice of converting errors into exceptions, then the module apparently causes a segmentation fault.  I'm not entirely sure how this happens.  It bit me because PHPUnit by default will convert PHP errors into exceptions.  But the problem isn't necessarily with PHPUnit -- consider the following code:

> <?php
> 
> error_reporting(-1);
> function handler($errno, $errstr, $errfile, $errline) {
>     throw new Exception($errstr, $errno);
> }
> set_error_handler('handler');
> 
> print "About to call mktime:\n";
> mktime();
> print "Called mktime\n";
> 
> ?>

The output with the built-in PHP mktime is:

> About to call mktime:
> PHP Fatal error:  Uncaught exception 'Exception' with message 'mktime(): You should be using the time() function instead' in /src/shp/temp.php:5
> Stack trace:
> #0 [internal function]: handler(2048, 'mktime(): You s...', '...', 10, Array)
> #1 /src/shp/temp.php(10): mktime()
> #2 {main}
>   thrown in /src/shp/temp.php on line 5

And with php-timecop it is

> About to call mktime:
> Segmentation fault (core dumped)

This seems to me like a bug in timecop.  For my purposes, I can (and probably will) workaround the issue, but I figured I'd submit a bug report anyway.

**Comment by hnw** [comment]
Thanks for the great bug report! Fix landed in trunk.
