### ISSUE TITLE
Any plan to add timecop formula to Homebrew?

### ISSUE THREAD

**Issue by keitap** [hnw/php-timecop#11]
If you don't mind, I will send a pull-request to them. Is it okay?

**Comment by hnw** [comment]
Awesome suggestion! Yes, thank you very much.

**Comment by keitap** [comment]
@hnw  -san, They have just merged my pull-request and timecop is added to homebrew-php.
ref: https://github.com/Homebrew/homebrew-php/pull/3169

Thank you for making such a nice extension :)
