### ISSUE TITLE
Publishing on PECL

### ISSUE THREAD

**Issue by IonBazan** [hnw/php-timecop#15]
I would like to thank you for this fantastic extension. It helped our company easily test time-aware features.
Are there any plans for publishing this extension in PECL or PEAR2? It would simplify the installation procedure.

**Comment by ababushkin** [comment]
Agreed this would be a great addition to standard PECL libraries.

**Comment by cweiske** [comment]
It is on pecl now: http://pecl.php.net/package/timecop

**Comment by ababushkin** [comment]
Awesome!

**Comment by hnw** [comment]
Now we publish php-timecop on PECL. Thanks for opening the issue and all the thumbs up!

As unexpected side-effects, we are able to support Windows platform thanks to PECL's DLL build system.
