### ISSUE TITLE
Causing a Segmentation Fault early on in a large test suite

### ISSUE THREAD

**Issue by scottdavis** [hnw/php-timecop#4]
I just installed php-timecop and went to run my tests suite to make sure nothing was broken it got about 12 tests in and died to a Segmentation Fault. Everything worked fine again after I commented out timecop.so in the ini file. Im not sure where to start debugging this but not that i didn't actually use timecop yet and it was still causing the seg fault

PHP 5.3.27 (cli) (built: Jul 12 2013 09:55:34)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2013 Zend Technologies
    with Xdebug v2.2.3, Copyright (c) 2002-2013, by Derick Rethans

**Comment by hnw** [comment]
Please reopen if reproduced on the current version.
