### ISSUE TITLE
PHP8 support?

### ISSUE THREAD

**Issue by Misosooup** [hnw/php-timecop#54]
Getting quite a number of errors when trying to install with PHP 8.2

```
/tmp/pear/temp/timecop/timecop_php7.c: In function 'get_formatted_mock_time':
/tmp/pear/temp/timecop/php_timecop.h:183:62: error: expected ')' before 'TSRMLS_CC'
  _call_php_method_with_0_params(obj, ce, method_name, retval TSRMLS_CC)
```
seems like TSRMLS_CC is the issue. Is there any further support for this library for PHP8?

**Comment by IonBazan** [comment]
This library was not updated for 4 years now, so I don't think it will be updated to support PHP 8, especially that it was aimed to handle legacy applications. Meanwhile, you can rely on some other approaches for testing - either [nesbot/carbon](https://packagist.org/packages/nesbot/carbon) or [psr/clock-implementation](https://packagist.org/providers/psr/clock-implementation).

**Comment by Misosooup** [comment]
alright, thanks. Will look into those.
